- circle.yml
- glide.lock
- glide.yaml
> add glide config and deps

- check/check_http.go
- check/check_tcp.go
- check/checkresult.go
- commands/serve.go
- glide.lock
- glide.yaml
- types/config.go
> r4r: TCP tweaks

- protocol/methods.go
- types/session.go
@jjbuchan your question inspired me to clean this up a bit
> Declare constants for AEP<->poller protocol methods

- check/checkresult_metrics.go
- check/unmarshal.go
- hostinfo/unmarshal.go
- protocol/check/check.go
- protocol/check/http.go
- protocol/check/ping.go
- protocol/check/tcp.go
- protocol/hostinfo/cpu.go
- protocol/hostinfo/hostinfo.go
- protocol/hostinfo/memory.go
> Add copyright/license header to new protocol refactored files

- commands/serve.go
- types/connection_stream.go
- types/session.go
> fix shutdown logic

- protocol/frame.go
- protocol/messages.go
- types/scheduler.go
- types/session.go
> Correcting for encoding of FrameMsg composing FrameMsgCommon

- check/check_http.go
- check/checkresult_metrics.go
- check/unmarshal.go
- config/config.go
- utils/status.go
* Add a statusline object
* Parse the URL to inject the IP address within and set the Host header
* Fixes some of the lint warnings on docs
> http check tweaks

- check/checkresult_metrics.go
- protocol/methods.go
the old post method is not going to be compatible with how we need to push metrics. the demo branch in ELE contains the server-side code.
> change to check_metrics.post_multi

- protocol/frame.go
saw this in the @itzg 's PR... simplifies the logic around the increment
> simplify the atomic increment

- circle.yml
- glide.lock
- glide.yaml
- hostinfo/hostinfo_cpu.go
- hostinfo/hostinfo_filesystem.go
- hostinfo/hostinfo_memory.go
- hostinfo/hostinfo_processes.go
- hostinfo/hostinfo_system.go
- hostinfo/hostinfo_test.go
- hostinfo/unmarshal.go
- poller/session.go
- protocol/hostinfo/cpu.go
- protocol/hostinfo/filesystem.go
- protocol/hostinfo/hostinfo.go
- protocol/hostinfo/memory.go
- protocol/hostinfo/processes.go
- protocol/hostinfo/system.go
- protocol/metric/metric.go
reach works with a poller attached.
> more hostinfo fixes

- circle.yml
* remove release section from CircleCI build to avoid collisions
> Releases are now performed via TravisCI

- config/endpoint_config.go
@dimtruck I found this while reviewing https://github.com/racker/rackspace-monitoring-poller/pull/49
> Need to check for JSON unmarshal errors in endpoint config file

- .travis.yml
- README.md
- combine-coverage.sh
Borrowed heavily from
https://mlafeldt.github.io/blog/test-coverage-in-go/
> (feat): Combine coverage restuls and push to coveralls

- check/check.go
- check/check_http.go
- check/check_http_test.go
- check/check_tcp.go
> refactor readLimit

- check/check.go
- check/check_http.go
- check/check_http_test.go
- check/check_tcp.go
- check/check_tcp_test.go
- utils/certs.go
- utils/status.go
> add tls metrics to tcp

- hostinfo/hostinfo.go
- hostinfo/hostinfo_cpu.go
- hostinfo/hostinfo_cpu_test.go
- hostinfo/hostinfo_filesystem.go
- hostinfo/hostinfo_filesystem_test.go
- hostinfo/hostinfo_memory.go
- hostinfo/hostinfo_memory_test.go
- hostinfo/hostinfo_processes.go
- hostinfo/hostinfo_processes_test.go
- hostinfo/hostinfo_system.go
- hostinfo/hostinfo_system_test.go
- hostinfo/hostinfo_test.go
- poller/session.go
* Remove BuildResult
* Use Asserts in unit tests
> cleanup hostinfo

- .travis.yml
- poller.go
* Sets the version from the built tag
> add a version command

- poller/connection.go
- poller/connection_stream.go
- poller/connection_stream_test.go
- poller/connection_stream_whitebox_test.go
- poller/poller.go
- poller/poller_mock_test.go
Doesn't yet use any error conditions for selection...still pondering where we'd track those in EleSession or EleConnection.
> Compute best connection for metrics posting based on latency (CMC-1354)

- README.md
- check/pinger.go
- contrib/endpoint-agents/pzA/agentA/checks/http_rackspaceMon.json
- endpoint/agent.go
- endpoint/agent_tracker.go
- endpoint/basic_server.go
* additional cleanup
* added a sample HTTP check
> Use privileged ICMP when running as root

- Makefile
- pkg/debian/repo/conf/distributions
Adds support for reprepro and rclone to push to cloudfiles.
> add reprepro-scripts + rclone

- glide.lock
- glide.yaml
Seeing these types of fixes, https://github.com/shirou/gopsutil/pull/320 , made me realize we probably need to bump up our gopsutil (and any others).
> Upgrade gopsutil

- config/config.go
- poller/connection_stream.go
reconnect logic wasn't working
> fix reconnect logic

- check/check.go
Reset a few HTTP check metric types to string (from number).
> Fix a few http metric types

- poller/entry.go
- poller/poller.go
I'll also continue to investigate a little deeper at where it gets hung during graceful shutdown.
> On SIGTERM start a timer to force exit

- poller/connection_stream.go
A nit I noticed while investigating shutdowns :)
> Adding log prefix to runRegistrationMetricsCoordinator

- check/check.go
- check/check_tcp.go
- check/checkresult_metrics.go
- check/checkresult_test.go
- docs/poller-api.adoc
- docs/poller-api.yml
- poller/scheduler.go
- protocol/messages.go
* also added debug log post-reconcile in the scheduler
> Structure check result metrics with 2-tuple at resource/dimension

- .travis.yml
- check/check_ping.go
- poller/connection.go
- poller/connection_stream.go
- poller/connection_stream_test.go
- poller/poller.go
- poller/poller_mock_test.go
- poller/session.go
- poller/session_test.go
- utils/events.go
> Fix metrics post before auth

- config/config.go
- config/config_test.go
- endpoint/agent.go
- poller/entry.go
- protocol/messages.go
- protocol/messages_test.go
...but @rphillips feel free to veto this
> Flatten handshake's feature flags to array of objects

- poller/session.go
> add prefix to far end log message

- Makefile
- README.md
- check/check.go
- check/check_http.go
- commands/serve.go
- commands/verify.go
- config/constants.go
- contrib/endpoint-agents/pzA/agentA/checks/http_monRaxNet.json
- pkg/debian/upstart_default.cfg
- poller.go
This is not the formal documentation area, but at least an informal installation procedure would be nice to have in the README.
> Added an introductory install section to the README

- check/check.go
- check/check_http.go
> io.LimitReader fix

- poller/connection_stream.go
- poller/poller.go
- poller/poller_mock_test.go
- poller/scheduler.go
- poller/scheduler_test.go
...when last connection goes down
TODO:
> Introduce a Reset capability on the scheduler and conn stream uses it

- glide.lock
- glide.yaml
- poller.go
- poller/connection.go
- poller/connection_stream.go
* improved clarity of conn deregistered on ones not fully authenticated
> Use ForceFormatting to include prefix in file based logging (CMC-1497)

- check/check_ping.go
- check/pinger.go
> Hand-encode ping request body to stay within 64 byte google.com limit

- Makefile
- contrib/vms/Vagrantfile
- contrib/vms/provision.sh
> Generate a DEB specific for upstart vs systemd based systems

- DEVELOPMENT.md
- README.md
- pkg/generic/sample.cfg
* also splits out the developer specific parts of the README
> Adding token, zone, and check usage to README

- .travis.yml
- utils/rlimit.go
- utils/rlimit_stub.go
Since Rackspace also manages Windows nodes.
> Add windows binary

- Dockerfile
> Update dockerfile versions

- poller/connection.go
> Don't log proxy credentials
