racker/rackspace-monitoring-poller

- circle.yml
From `gox -h`
```
Platforms (OS/Arch):
The operating systems and architectures to cross-compile for may be
specified with the "-arch" and "-os" flags. These are space separated lists
of valid GOOS/GOARCH values to build for, respectively. You may prefix an
OS or Arch with "!" to negate and not build for that platform. If the list
is made up of only negations, then the negations will come from the default
list.
```
> gox OS options need to be space separated

- circle.yml
gox needed to invoked within the codebase, like the go invocation itself
> Fix gox invocation during CircleCI deploy

- check/check_http.go
Saw this technique with golang 1.7. It uses a context to set a timeout on the entire http transaction. Simplifies the code, and is generally pretty cool.
> cleanup the http timeout using a context

- README.md
- check/check.go
- check/check_http_test.go
- check/check_ping_test.go
- check/check_tcp_test.go
- check/check_test.go
- check/unmarshal.go
- poller/connection_stream.go
- poller/scheduler.go
@goru97, @tpboudreau , @GeorgeJahad I was looking at the session go-loops and speculated this change might help for check commit/update logic. Feel free to chop it up or rip it out later if not applicable.
> Add sub-context to enable cancellation of checks

- check/check_tcp_test.go
- utils/test.go
A normal test run (with this change) looks like
```
/usr/local/go/bin/go test -v github.com/racker/rackspace-monitoring-poller/check -run ^TestTCPRunSuccess$
time="2017-02-13T14:22:05-06:00" level=info msg="New check chPzATCP" details="{\"port\":51818,\"ssl\":false}" disabled=false ipaddresses=map[default:127.0.0.1] period=30 target_alias=default target_hostname= target_resolver= timeout=15 type=remote.tcp
time="2017-02-13T14:22:05-06:00" level=info msg="Running TCP Check" address="127.0.0.1:51818" id=chPzATCP ssl=false type=remote.tcp
time="2017-02-13T14:22:05-06:00" level=info msg="disconnecting 127.0.0.1:51819"
ok       github.com/racker/rackspace-monitoring-poller/check     0.150s
```
however one of the sporadic failures was missing that "disconnecting" log: …
> Fixing sporadic failures in TestTCPRunSuccess

- poller/session.go
Crash: 
```
goroutine 16 [running]:
panic(0x43e2520, 0xc4200100e0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
time.(*Timer).Stop(0x0, 0xc42029a100)
/usr/local/go/src/time/sleep.go:66 +0x26
github.com/racker/rackspace-monitoring-poller/poller.(*EleSession).handlePollerPrepare(0xc420248000, 0xc4202de000)
/Users/dimi5963/projects/maas/go/src/github.com/racker/rackspace-monitoring-poller/poller/session.go:304 +0x342
github.com/racker/rackspace-monitoring-poller/poller.(*EleSession).handleFrame(0xc420248000, 0xc4202de000, 0x1, 0x1)
/Users/dimi5963/projects/maas/go/src/github.com/racker/rackspace-monitoring-poller/poller/session.go:259 +0x38b
github.com/racker/rackspace-monitoring-poller/poller.(*EleSession).runFrameHandlingAndTimeout(0xc420248000) …
```
> add nil check for s.prepDetails.prepareToEndTimer

- poller/connection.go
With this change the logs will contain pairings such as
```
time="Fri, 31 Mar 2017 12:08:43 CDT" level=info msg="Connecting to agent/poller endpoint" timeout=10s 
time="Fri, 31 Mar 2017 12:08:44 CDT" level=info msg=Connected remote_address=50.57.194.13:443 
time="Fri, 31 Mar 2017 12:08:44 CDT" level=debug msg="frame handling starting" 
time="Fri, 31 Mar 2017 12:08:44 CDT" level=debug msg="send starting" 
time="Fri, 31 Mar 2017 12:08:44 CDT" level=debug msg="read starting" 
time="Fri, 31 Mar 2017 12:08:44 CDT" level=debug msg="socket send" data="{\"v\":\"1\",\"id\":1,\"target\":\"endpoint\",\"source\":\"cfb694c3-2466-4c42-9901-e23bfb8788d5\",\"method\":\"handshake.hello\",\"params\":{\"token\":\"fd0626aa72e7cd27cbd5f68e9668782f83b91983f1ca1643d5627f13de7fdd74.777788\",\"agent_id\":\"-poller …
```
> Balance the connection's "Connected" log with "Disconnected"

- config/config.go
- contrib/local-endpoint.cfg
- contrib/metrics/Dockerfile-prometheus
- contrib/metrics/docker-compose.yml
- contrib/metrics/prometheus.yml
- glide.lock
- glide.yaml
- poller/connection.go
- poller/entry.go
- poller/metrics.go
- poller/scheduler.go
This PR is an **evaluation** of integration with Prometheus statistics gathering backend. There are many frameworks available and various techniques to gathering metrics, such as push vs pull/scrape. The current code changes evaluate specifically a metric-push methodology due to private network constraints around poller deployments.
Statsd and Graphite are both important frameworks/backends to consider in amongst this approach. One reason for this particular WIP evaluation is that Prometheus already supports a [statsd exporter](https://github.com/prometheus/statsd_exporter) and a [graphite exporter](https://github.com/prometheus/graphite_exporter). Prometheus has its roots in golang and appears to be emerging as the defacto standard for Go based applications.
```
cd contrib/metrics …
```
> Initial integration of Prometheus

- check/check_http.go
The golang http client will, by default, decode compressed responses.
> remove accept-encoding header

- check/check.go
- check/check_http.go
* should be represented as a zero or one (it gets converted later to a
true/false)
* Change the LimitReader to read limit+1 to allow for detection of the
truncation
> fixes the truncated value

- config/config.go
- config/constants.go
- poller/connection.go
- poller/connection_stream.go
- poller/connection_stream_test.go
- poller/connection_test.go
- poller/entry.go
This change allows for the `ele-server-agent-endpoint` to be run locally in an IDE, such as IntelliJ, and connect to it with a locally running poller. In that scenario the poller is connecting directly to the NodeJS process in which case no TLS termination is involved.
The poller config ends up looking like:
```
monitoring_token *****.*****
monitoring_endpoints localhost:50040
monitoring_private_zones pz...
```
> Add dev-time option to use a non-TLS connection to agent endpoint

- contrib/vms/.gitignore
- pkg/generic/logrotate.cfg
- pkg/generic/service.systemd
also
* change logrotate to use pidof to generically find process to HUP
Internal users were tweaking the service definition to write to the /var/log anyway, but the logrotate wasn't working then because there's no pid file with systemd.
FYI, [here's the pidof command's man page](http://manpages.ubuntu.com/manpages/zesty/man8/pidof.8.html).
> systemd service needs to also log to /var/log

- check/pinger.go
This is a hopeful-fix to match the characteristics of `ping` where by default it pads out the ICMP payload to 64 bytes (when combined with the 8 bytes of ICMP header).
> Pad out the ICMP payload to 64 bytes since that seems to be standard

- pkg/debian/service.upstart
Avoid the use of `start-stop-daemon` since it interferes with the upstart environment expectations.
> Fix upstart exec to ensure proper restart

- check/check_ping.go
- check/check_ping_test.go
- check/pinger_test.go
I only encountered this issue when running `go test ./check/...` from the command-line. The ordering was apparently different running in IntelliJ and over in TravisCI.
> check_ping_test needs to put back the PingerFactory since it is global

- .travis.yml
- check/check_ping.go
- check/check_ping_test.go
- check/pinger.go
- check/pinger_test.go
Also
* ensure read timeouts don't get latched and mislead alert processing
* increase TestPinger_Concurrent concurrency, but also tolerate missed packets
* fix TestPingCheck_PartialResponses's handling of the partial packet loss, which is not for the check to deem "unavailable"
FYI, packet loss pinging localhost can also be seen using `ping`:
```
rm -rf /tmp/pings; mkdir -p /tmp/pings; cd /tmp/pings; for i in $(seq 0 1 50); do
ping -c 5 -i 0.1 localhost > /tmp/pings/out-${i} &
done
grep "packet loss" /tmp/pings/*
```
> Pinger needs to also handle write timeout

- check/check.go
- check/check_http_test.go
- check/check_tcp_test.go
Adds the `cert_end_in` metric which compared the `cert_end` time to the current time.
In tests we allow for a 2s difference compared to what we expect in case test slowness occurs.
> Add cert_end_in metric to ssl checks

- Makefile
Add to rather than replace the CloudFiles content via the rclone operation.
For CMC-1705
> Retain rclone'd structure to allow migration

- check/check_http.go
- commands/verify.go
Even when running the `verify` sub-command with the new `repeat` option I was able to observe an apparent leaking of FDs (example below). In [http.Transport](https://golang.org/pkg/net/http/#Transport) keep-alive is enabled by default and it appears the frequent re-connection is defeating/confusing Go's garbage collection of those connections.
```
COMMAND     PID     USER   FD      TYPE             DEVICE   SIZE/OFF       NODE NAME
___verify 13545 geof0549  cwd       DIR                1,4        224    4861757 /Users/geof0549/go/src/github.com/racker/rackspace-monitoring-poller/contrib/endpoint-agents/pzA/agentA/checks
___verify 13545 geof0549  txt       REG                1,4   15173348 8598597756 /private/var/folders/xf/96hzdx9n24s22r3_2wnw4_bxns4t3x/T/___verify_check__repeat_ …
```
> Disable HTTP keep-alive to avoid remote.http fd leak (CMC-1826)

- .travis.yml
- glide.lock
- glide.yaml
...since gopsutil is important for hostinfo gathering.
I also wanted to kick out a new minor release to test out an update to apt repo signing version for verifying CMC-1728.
> Refresh dependencies to pick up newest gopsutil

- check/pinger.go
* Windows doesn't allow applications to use ICMP over UDP at all
* The UID==0 approach we use doesn't properly test for Windows running in elevated privileges
so...just always assume and use privileged mode on Windows. It's OK if it's a bad assumption since the user gets a meaningful error in the logs:
```
An attempt was made to access a socket in a way forbidden by its access permissions.
Unable to create ICMP listener
```
> Always run ping as priveleged mode on Windows (CMC-1987)

- Gopkg.lock
- Gopkg.toml
- config/config.go
- poller/connection_stream.go
- poller/connection_stream_test.go
Fixes https://jira.rax.io/browse/CMC-2237
This is the equivalent fix as this PR
https://github.com/virgo-agent-toolkit/virgo-base-agent/pull/193
We have observed that the long-lived AEP connections via a proxy will sometimes get into a hung state where the poller can't tell the TCP connection is closed yet communication is no longer functional over the connection.
As mentioned in the PR above, the root cause was never determined but a "solution" is to enforce a max age on the connections (2 days plus up to 1 day of jitter) and force the connections to get re-established via the proxy.
Like the agent approach, the jitter is calculated per connection to the AEP, so it is very unlikely that more than one out of the typical three AEP connections would ever be re-connecting at a time.
> Enforce a max age on connections to avoid proxy hanging on those

- Makefile
When performing a release of the PR https://github.com/racker/rackspace-monitoring-poller/pull/189 the build's invocation of reprepro reported the error:
```
using deb packager...
created package: build/rackspace-monitoring-poller_0.2.41-0_x86_64_upstart.deb
mkdir -p build/repos/ubuntu-14.04-x86_64/conf
sed -n -e "p" pkg/debian/repo/conf/distributions > build/repos/ubuntu-14.04-x86_64/conf/distributions
reprepro -b build/repos/ubuntu-14.04-x86_64 includedeb cloudmonitoring build/rackspace-monitoring-poller_0.2.41-0_x86_64_upstart.deb
Error looking at 'build/rackspace-monitoring-poller_0.2.41-0_x86_64_upstart.deb': 'x86_64' is not one of the valid architectures: 'amd64 source'
```
Apparently the resulting architecture part of the name has always been `amd64` looking at the prioro release …
> Use amd64 instead of x86_64 for input deb file for reprepro
